# data
data_dir: ./data/
token_type: char
batch_size: 32
seq_len: 10
nworker: 2

# model t, g, r
model_type: t
d_model: 8
num_heads: 2
hidden_size: 128
num_layers: 2

# training
lr: 0.001
wd: 0.0001
num_epochs: 20

# save
loss_path: ./loss.png
model_path: ./model.pth